#!/usr/bin/env python3

import os

import cherrypy

from cc_pathlib import Path

import musich.server

musich_root_dir = Path(os.environ["MUSICH_root_DIR"])

cherrypy.config.update({
	'server.socket_host': '192.168.1.105',
	'server.socket_port': 45080,
}) # global config
	
musich_config = {
	'/': {
		'tools.staticdir.root': str(musich_root_dir),
	},
	'/_static' : {
		'tools.staticdir.on': True,
		'tools.staticdir.dir': "static",
	}
}


cherrypy.tree.mount(musich.server.MusishServer(), '/', config=musich_config)

cherrypy.engine.start()
cherrypy.engine.block()
