#!/usr/bin/env python3

import os

from cc_pathlib import Path

from musich.catalog import MusichCatalog

catalog_dir = Path(os.environ["MUSICH_catalog_DIR"])

u = MusichCatalog(catalog_dir)
u.update()

k_lst = [
	[key,] + [f"{k}={v}" for k, v in u.c_map[key].items()] for key in sorted(u.c_map)
]

(u.index_pth.parent / u.index_pth.fname).with_suffix('.tsv').save(k_lst)
(u.index_pth.parent / u.index_pth.fname).with_suffix('.tsv.br').save(k_lst)
(u.index_pth.parent / u.index_pth.fname).with_suffix('.json').save(u.c_map)
