#!/usr/bin/env zsh

if [[ -d ${MUSICH_root_DIR} ]]
then
	if [[ ! -d ${MUSICH_root_DIR}/py3venv ]]
	then
		pushd ${MUSICH_root_DIR}
			python3 -m venv py3venv
			source ${MUSICH_root_DIR}/py3venv/bin/activate
			sudo apt update
			sudo apt install libcairo2-dev libgirepository1.0-dev gir1.2-gtk-3.0 python3-gdbm
			pip3 install cherrypy pygobject mutagen brotli
		popd
	fi
fi
