#!/usr/bin/env python3

import os

import cherrypy

from cc_pathlib import Path

import musich.local
import musich.catalog
import musich.queue

root_dir = Path(os.environ["MUSICH_root_DIR"]).resolve()
static_dir = Path(os.environ["MUSICH_static_DIR"]).resolve()

cherrypy.config.update({
	'server.socket_host': '127.0.0.1',
	'server.socket_port': 45081,
})
	
musich_config = {
	'/': {
		'tools.staticdir.root': str(root_dir),
	},
	'/_static' : {
		'tools.staticdir.on': True,
		'tools.staticdir.dir': "static",
	}
}

musich_catalog = musich.catalog.MusichCatalog()


musich_obj = musich.local.MusichLocal(static_dir, musich_catalog)

cherrypy.tree.mount(musich_obj, '/musich', config=musich_config)

cherrypy.engine.start()

musich_obj.m_ply.loop()
cherrypy.engine.block()
